### PR TITLE
Proper MJPEG support for the preview image

### PR DESCRIPTION
**Pull request by pyjamasam**
Updated the preview video to use proper multipart jpeg encoding.

### CODE REVIEW

**Comment by pyjamasam** [comment]
Also realized that I fixed up the dropdowns in the settings area to actually push their changes on change (so you don't have to click to make the change and then click again to send to the server - onchange instead of onclick for the select's)

**Comment by spikedrba** [comment]
fwiw, I was talking to somebody else it seems that setting a css background-image property will work to continuosly update the picture, making the whole timeout and img.src setting business unnecessary (this seems to also work well cross platform and on mobile). You can see an example here (look at the JpegStreamHandler class):

https://github.com/CoderBotOrg/coderbot/blob/develop/viz/streamer.py

the unavailable img stuff would then have to be rewritten as changing a css property.

And thanks for fixing the on-change, I was about to submit a patch for the same thing, it really confused me in the beginning, thought my settings weren't working.

**Comment by roberttidey** [comment]
Thanks for this, both the MJPEG and settings change. I am testing those.

**Comment by roberttidey** [comment]
OK to proceed with this pull, Silvan?

**Comment by silvanmelchior** [comment]
Wasn't able to look at it, but if you had, then I would say pull ;)

**Comment by silvanmelchior** [comment]
Just one thing: why do we need cam_pic and cam_pic_new? If you say it works, we could replace the old cam_pic with this one.

**Comment by roberttidey** [comment]
cam_pic_new feeds mjpeg to browser. cam_pic still feeds motion. I'm not sure if motion could use the new one. Probably safer to leave as is for the moment.

Could change name of cam_pic_new at some point to make it clearer

**Comment by roberttidey** [comment]
Forum user reports live preview not working on iOS Chrome / Safari when using MJPEG stream. Any thoughts?

**Comment by spikedrba** [comment]
confirmed, it's a known problem (been there quite a while):

https://discussions.apple.com/thread/4347848

I have an older running version of the code on a camera and it displays just fine in safari. Master however on another testing camera does not work. In that same thread luckily there seems to be a working solution.

Here's a patch I just tried out that works for me:
```
39c39
< 	echo "Content-type: image/jpeg\n\n";
---
> 	echo "Content-type: image/jpeg\r\n\r\n";
44a45
> 	echo "\r\n\r\n";
47c48
< }
\ No newline at end of file
---
> }
```
I've tried with just \n's and only one or various combos and that's the only one that worked for me.

**Comment by pyjamasam** [comment]
Having a \r\n\r\n after the content type header would in fact be then
correct fix. It signify she end of the http headers and the start of the
body of the response.

Also I just noticed the code I added has
+ echo "Content-type: image/jpeg\n\n";
Should be at a minimum \n\r and not a double \r\n

I can make a new pull request with the fix if you'd like, or you can just
change the \n\n to \r\n\r\n

Chris.

**Comment by pyjamasam** [comment]
I apologize for the horrid content of the previous comment. Autocorrect kicking my butt while responding on my phone. 

Chris.

**Comment by roberttidey** [comment]
Thanks. I've pushed that

**Comment by roberttidey** [comment]
Couple of forum users still having no success even with this change.

**Comment by pyjamasam** [comment]
**The following browsers are working**
*OS X*
Chrome: Version 42.0.2311.82 beta (64-bit) (latest)
Safari: Version 8.0.5 (10600.5.17) (latest)
Firefox: 36.0.4

*Windows 7*
Chrome: Version 42.0.2311.82 beta-m (latest)
Firefox: 12.0, 36.0.4

*IOS*
Safari: IOS 8.3

**Browsers that aren't working**
*OS X*
Firefox: 37.0.1 (latest) - shows a single frame but doesn't update after that

*Windows 7*
IE: 10.0.9200.16635 - hangs the browser
Firefox: 37.0.1 (latest) - shows a single frame but doesn't update after that

*IOS*
Chrome: 41.0.2272.58 - never shows anything but the "loading" image

I'll do some more digging and see what I can come up with with respect to Firefox and IE.  My guess is they are related problems.

chris.

**Comment by roberttidey** [comment]
Great info. OK. For me to post that on forum or do you want to do it?

**Comment by pyjamasam** [comment]
Not sure of my current forum registration state.  So if you don't mind could you cross post it?

I have noticed that a working mjpeg stream (as in working in firefox at least) is sending a content-length header in each of the multipart chunks.  Going to see if that makes a difference.  I'll report back my findings.

chris.

**Comment by silvanmelchior** [comment]
I suggest to use cam_pic.php as long as the issue isn't solved, otherwise all users except the ones regulary checking the forum could be confused.

**Comment by pyjamasam** [comment]
Code that works in everything but IE and Chrome on IOS (well haven't tested in android as I don't have any devices with it) is in pull request #53

As a side note though, I don't think its going to work in IE ever.  No examples I can find online (for mjpeg) work in IE.

While I really like the mjpeg support for things like off-board motion integration, we might want to look at a better rate limited (based on preview frame rate) javascript version (like the original solution).  This would give the most browser support, and we could still offer the mjpeg out (as a separate URL) for those who want to use it in things like openCV of motion on another system.

The bandwidth savings from syncing with the framerate could be achieved in javacsript in a similar fashion (just sleeping for the right amount of time between fetches).

chris.

**Comment by roberttidey** [comment]
OK. Here's my proposal for the moment.

1) Merge in updated MJPEG to increase compatibility. Leave index.php + additional jpgs in place
2) revert default operation to cam_pic.php. I tried this by reverting just the script.js where init effectively defines the operational mode. That seems to be OK. It was actually broken in my 37.01 Firefox before (I thought it was working but it wasn't). Reverting just script showed standard cam_pic.php operation
3) Adjust script so that it can work either way, i.e. mjpeg can be activated.
4) Main question for me is what controls item 3). Possibilites are local config file or a cookie.

**Pull request merged**
