### PR TITLE
Install Update fix

### PR DESCRIPTION
**Pull request by miraaz**
Its test comits. If needed comits updated and script runs himself again. That way install and update using always new comit version and not needed run scipt twice manually, when comits not mach!

### CODE REVIEW

**Comment by miraaz** [comment]
OMG! Can i have write acess please!?

**Comment by roberttidey** [comment]
Just want to check on something with you before merging this in.

The fn_git_pull function is being called from the install case. The function runs the script again but doesn't the rest of the install case run as well after the function returns.

**Comment by miraaz** [comment]
The fn_git_pull function is being called from the install case and called also from the update case. The function runs script again only when finds local and network not equal. If local and network already equal its going to rest script. But in first run if not equal its updates local and after that network and local already equal. That means in second run its runs already new updated script and finds all updated and runs now rest install. I tested that all already and worked perfectly ;)

**Comment by miraaz** [comment]
Without that fix i needed run install script twice get same result if in git repo have already new version!

**Comment by roberttidey** [comment]
Yes. I understand the principle but I don't know what bash does when you call $0 in the check. If bash completely abandons the execution of the current script then I understand the sequence. If,bash executes the $0 but then returns to the install code from the first pass the net result would be that it installs twice which would work but is a bit messy.

**Comment by miraaz** [comment]
$0 calls already updated script not runs old again. It not installs twice. It updates first and not run  rest install. Second pass running already new script.

**Comment by miraaz** [comment]
$0 is like call ./RPi_Cam_Web_Interface_Installer.sh it not running script what is in memory. It calls script again.

**Comment by miraaz** [comment]
Yes its little messy run install script again if install script himself not updated in network git. I to not know how test install script himself needed update 0or not. I test whole repo. But safe to run it again if it maby already updated

**Comment by roberttidey** [comment]
Running script again is not the issue. I am fairly certain the install case can run twice

Trying a simple test with a file test.sh like 
#!/bin/bash
echo 'called' $1
if [ "$1" = "fred"  ]; then
$0 
fi
echo 'test' $1

If I call this with
./test.sh fred
 then the final echo gets called twice. Once when the script calls itself and the if fails and then again when it falls through the if.

Maybe what is needed is to change the install verb so the install just does a check an optional update and then always calls the itself with an action like install1 and this is what does the real operations. That way the

**Comment by miraaz** [comment]
Hmm but if we add exit?

#!/bin/bash
echo 'called' $1
if [ "$1" = "fred" ]; then
$0
exit
fi
echo 'finalscript'

**Comment by roberttidey** [comment]
Yes, exit would work as well. You are just trying to prevent it from getting into the actions twice.

**Comment by silvanmelchior** [comment]
You also might consider to move the update-instructions to a new
switch-case (for example update2) and then update updates the installer and
then calls itself with update2.

**Comment by miraaz** [comment]
Now i think what happends when internet not acsessible but we still want install...? And if user no want update but wants install old version...? Grrr! Its not possible see all possipilities what user wants lol! I mast think and test more...!

**Comment by miraaz** [comment]
Got idea! Maby we go update and upgrade way? Like working aptitude update and aptitude upgrade?
I mean we remove "git pull" in install case at all. Then rename "update)" to "upgrade)". Now making new call "update)" where we compare and pull git if needed.
What you think my idea? If you like it i make bach.
So we pulling only when calling "update)" and remove pulling install and upgrade case.
nb. Founded already way how stop "update)" process if error happens (no internet example) and script not going to loop.

**Comment by miraaz** [comment]
Newer is aviable. Not needed that.

**Pull request closed without merging**
