### PR TITLE
Fix for update script to use git pull

### PR DESCRIPTION
**Pull request by quavoce**
Hi Robert,
I saw a number of forum posts where users haven't been able to update using the update.sh script. I tried this myself and had the same problem, so after a bit of investigation I found that "git fetch origin master" was failing and that "git pull" would work instead. 
For full details please see this post: https://www.raspberrypi.org/forums/viewtopic.php?p=1173370#p1173370

### CODE REVIEW

**Comment by roberttidey** [comment]
Hmmmm. Thanks for the pull request. update originally used git pull but that was giving errors when a local file had changed or if an unstaged file had been added which can happen. git pull would then complain that the repository was out of sync and therefore wouldn't do the merge. I changed it to git fetch to try to avoid this but it looks like this only affects the local git repository (under .git) and not the working files.

I must admit I rarely test the update mechanism as the files are always being changed locally in my development machines.

There are many git suggestions on how to resolve this. The following seems to be the easiest.
`git fetch origin master
git reset --hard origin/master`

If that works then I'll update the script like that

**Comment by quavoce** [comment]
Ah yes, I remember that too - the "chmod u+x *.sh" command used to modify the files and cause a git error, but I didn't realise it was using git pull back then. 

I've just manually tested your alternative suggestion and can confirm that works! I'll now add the code into update.sh and try that too.

`pi@garagecam:~/RPi_Cam_Web_Interface $ chmod 755 remove.sh
pi@garagecam:~/RPi_Cam_Web_Interface $ ls -al remove.sh
-rwxr-xr-x 1 pi pi 5309 Jun  6 18:30 remove.sh
pi@garagecam:~/RPi_Cam_Web_Interface $
pi@garagecam:~/RPi_Cam_Web_Interface $ git rev-parse HEAD
c02dab42899749746f8e84b624dfad0c7f651f94
pi@garagecam:~/RPi_Cam_Web_Interface $ git ls-remote -h origin master |awk '{print $1}'
a34051a6617d26c270ae906c48267be06329a1d1
pi@garagecam:~/RPi_Cam_Web_Interface $
pi@garagecam:~/RPi_Cam_Web_Interface $ git pull
remote: Counting objects: 43, done.
remote: Total 43 (delta 33), reused 33 (delta 33), pack-reused 10
Unpacking objects: 100% (43/43), done.
From https://github.com/silvanmelchior/RPi_Cam_Web_Interface
   c02dab4..a34051a  master     -> origin/master
Updating c02dab4..a34051a
error: Your local changes to the following files would be overwritten by merge:
	install.sh
Please, commit your changes or stash them before you can merge.
Aborting
pi@garagecam:~/RPi_Cam_Web_Interface $
pi@garagecam:~/RPi_Cam_Web_Interface $ git fetch origin master
From https://github.com/silvanmelchior/RPi_Cam_Web_Interface
 * branch            master     -> FETCH_HEAD
pi@garagecam:~/RPi_Cam_Web_Interface $ git rev-parse HEAD
c02dab42899749746f8e84b624dfad0c7f651f94
pi@garagecam:~/RPi_Cam_Web_Interface $ git reset --hard origin/master
HEAD is now at a34051a Add bcrypt option to htpasswd
pi@garagecam:~/RPi_Cam_Web_Interface $ git rev-parse HEAD
a34051a6617d26c270ae906c48267be06329a1d1
pi@garagecam:~/RPi_Cam_Web_Interface $ git ls-remote -h origin master |awk '{print $1}'
a34051a6617d26c270ae906c48267be06329a1d1
pi@garagecam:~/RPi_Cam_Web_Interface $`

**Comment by quavoce** [comment]
This now works in the update script, though I found I also needed to make the scripts executable again. I'll submit another pull request along with an updated startstop.sh script which handles watchdog resets. 
Thank you!

**Comment by roberttidey** [comment]
Thanks for trying that out and the startstop stuff. Now merged in

**Pull request merged**
