### PR TITLE
Improving loading of previews and keyboard navigation

### PR DESCRIPTION
**Pull request by macecchi**
Hey! 

I’ve been using this software for a long time and having to reload the entire page when navigating through the previews was something that really annoyed me.

I’ve refactored the preview.php code that handles the media to load it dynamically using JavaScript, so that:

- Loading a different preview does not reload the entire page - only the preview div
- The browsing history/URL remains valid
- You can navigate through the files using the arrow keys (left/right)
- The previous and next images are preloaded so that the navigation looks smoother

As a bonus, the HTML part from preview.php is a lot more readable now :)

I hope I got everything ok - it seems to be working well here (although I wasn’t able to test videos and tl a lot).

### CODE REVIEW

**Comment by macecchi** [comment]
Any feedbacks? @silvanmelchior @roberttidey

**Comment by roberttidey** [comment]
Hi, Thanks for these changes which look very good. I was just checking out before I merge them in.

Everything is looking good except when I select videos then they are being displayed at full captured resolution rather than controlled by the preview size. Image captures do obey the preview size.

**Comment by roberttidey** [comment]
Hi, Thanks for these changes which look very good. I was just checking out before I merge them in.

Navigating forward and back the images are changing but the text identifying the image is not. E.g. the bit immediately after Preview:

If I select a video then I think it is being displayed at full captured resolution rather than controlled by the preview size. Image captures do obey the preview size.

**Comment by macecchi** [comment]
Hey @roberttidey, thanks for merging that 😀

Sorry about that extra quote, hahaha.

The title seems to be updating normally here... Did you find out what is it?

**Pull request merged**
