### PR TITLE
add camera switch for compute module

### PR DESCRIPTION
**Pull request by 0legg**
Raspberry PI Compute module IO Board have possibility to connect two cameras. I made pull-request https://github.com/silvanmelchior/userland/pull/2 to support this in raspimjpeg library, this patch adds possibility to switch camera in web interface

### CODE REVIEW

**Comment by roberttidey** [comment]
silvan and I switched active raspimjpeg development to my github https://github.com/roberttidey/userland

Can you fork and make the raspimjpeg request from there? Then we can see about the web change.

**Comment by roberttidey** [comment]
Manually added to make camera_num selection optional. 0=off, 1=first, 2=second

**Comment by 0legg** [comment]
@roberttidey So, as the dual camera setup possible only for Compute module, I think camera_num should be splitted into two separate settings: enable dual camera and choose camera number. In this case, possibility to enable can be detected on install stage (grepping /proc/cpuinfo).

**Comment by roberttidey** [comment]
The intention with the change was indeed to allow installer to set this up. E.g. if installer wanted to support compute module then it sets value to 1 and from then on it can be controlled. Similarly for Pi it is 0 and stays that way. The detect could be an even better way that could potentially be done at run time.

I kept it as one config variable just to avoid too much growth in that area and I think it achieves the same effect. There is already a lot of variables in there.

**Comment by 0legg** [comment]
It makes sense. I'm now looking on install script and trying to figure out how to do better integration. From your point of view, what is the proper way to store this config? I can add check in configuration script, so camera_num will be set to 1 for Compute Module, and 0 for any other Raspberry Pi

**Pull request closed without merging**
