### PR TITLE
Motion stuff upgraded. Lot of changes...

### PR DESCRIPTION
**Pull request by miraaz**
Canged motion not replaces his config in Jessie (oldway). Now its changes conf in place. Its good to use same schema in old Wheezy?
I try bush that old installer live again and better when ever.
Fixed when no webservers installed then script stucked. (need all the time purge deb-s or i no find bugs)
Fixed Nginx finds also webroot and webport
Puted trap in "configure" menu so script not stuck when servers not installed.
Cosmetic tweaks.
Next step is implement Nginx port changing also. Currently we only finding port and show that.
Is Nginx using same .htaccess for security? Need find out and implement if possible...

### CODE REVIEW

**Comment by roberttidey** [comment]
I use the same in place motion technique for wheezy as well as jessie

**Comment by miraaz** [comment]
Ok tnx. I change Whreezy motion also. But i cant test both Whreesy and Jessye some time. That takes time test both,

**Comment by miraaz** [comment]
roberttidey you got my message in forum? What you think?

**Comment by roberttidey** [comment]
Thinking about it. The time filter helps quite a bit and I normally let auto-purge look after everything. If one has a lot of junk then it can be a lot quicker to select all then unclick the items you want to keep which is a bit like selecting and moving to a separate folder anyway

**Comment by miraaz** [comment]
Yes, but sometimes we do not know as clip is junk or not. We mast first look it. When its not junk, then we can send it in archive. Now i know useful clip is archived and i not need worry about it, i can delete that accidentally when i look what another 1500 clips contains...

**Pull request merged**
