### PR TITLE
Critical fix and start stop wo GUI

### PR DESCRIPTION
**Pull request by miraaz**
Move top was mistake! Script not run at all that way! My mistake!
Merge fast please!

### CODE REVIEW

**Comment by miraaz** [comment]
Sorry about that! I overworking myself!

**Comment by miraaz** [comment]
Oww help! 
If comment lines out in local installer i change it manually and now git bull not possible!
Have you idea how we resolve that problem now? 

From https://github.com/silvanmelchior/RPi_Cam_Web_Interface
 * branch            master     -> FETCH_HEAD
Updating a821b1d..d959cbe
error: Your local changes to the following files would be overwritten by merge:
        RPi_Cam_Web_Interface_Installer.sh
Please, commit your changes or stash them before you can merge.
Aborting

***************
*** ABORTED ***
***************

An error occurred. Exiting...

**Comment by miraaz** [comment]
We need way in update option, when local installer edited by hand, then update process overwrites installer script again and not generates error and abort! I do not know how do that right now.

**Comment by roberttidey** [comment]
Yes. I've not found Git very friendly in that area. It really likes to keep everything in sync. I am sure there is some git command line to achieve a revert (i.e. back to the real git hub code) but even with this I always end up in conflicts.

When I get into this situation (which often happens) then I just delete the RPi Cam install directory and re-clone from the beginning which achieves the same thing. Here we would lose the config.txt so it might be worth thinking out a process to effectively delete and re-clone while keeping config.txt

**Comment by miraaz** [comment]
Notice we not lose config.txt :). That is generated and not in git repo

**Comment by miraaz** [comment]
git checkout file_to_overwrite
not working. It puts back buggy installer what not running.

**Comment by miraaz** [comment]
Got one way fast fix. I write in forum fast. Please help with eng explain it.

**Comment by miraaz** [comment]
roberttidey i posted in forum way how fix. Please read it and fix my eng, so everyone understand it.

**Pull request merged**
