### PR TITLE
Added HD-ready and changed description for Full-hd

### PR DESCRIPTION
**Pull request by miraaz**
Added HD-ready selection and changed description for FULL-HD for bether understand.

### CODE REVIEW

**Comment by roberttidey** [comment]
Thanks. Just want to check if silvan is happy with change of wording

**Comment by silvanmelchior** [comment]
Thanks too. I think it would be better to change the order to full-hd, then
hd-ready and to add the Std-FOV into the Name. Something like this could be
good:

16:9 1080p Std FOV
16:9 720p Std FOV

What do you guys think?

**Comment by roberttidey** [comment]
Change order sounds good
Here would be my suggestion
"1920 1080 25 25 2592 1944">Select option...</option>
"1920 1080 25 25 2592 1944">Full HD 1920p 16:9 FOV</option>
"1280 0720 25 25 2592 1944">HD-ready 720p 16:9 FOV</option>
"1296 730 25 25 2592 1944">Medium   730p 16:9 FOV</option>
"1296 976 25 25 2592 1944">Max View  976p  4:3 FOV</option>
"768 576 25 25 2592 1944">SD TV 576p  4:3 FOV</option>
"1920 1080 01 30 2592 1944">Full HD Timelapse (x30) 1920p 16:9 FOV</option>

Where I added in a standard def TV which seems to work and may be useful for those who want to trade res / storage.

If we have HD Ready should we lose what I call Medium which exists today but is very close to HD Ready

**Comment by silvanmelchior** [comment]
Sounds good, I agree in removing Medium. Additionally, the FOV is also not
really necessairy and could be removed i suppose.

**Comment by spikedrba** [comment]
since this came up, maybe I'm confused about the 1296 976 mode, I saw a mention here (https://www.raspberrypi.org/documentation/hardware/camera.md), but querying the hw seems to suggest the mode should be1296x972, no 976.

See this for example:
https://www.raspberrypi.org/new-camera-mode-released/

sorry if I'm missing the point.

**Comment by roberttidey** [comment]
I hadn't noticed that. 972 would be correct for true 4:3. I tried that out and seems OK so I've changed to that. Just in time too; I was about to push it.

**Comment by roberttidey** [comment]
Merged in manually with additions

**Pull request closed without merging**
