### PR TITLE
RPi_Cam_Web_Interface_with_ServoBlaster_pan_tilt

### PR DESCRIPTION
**Pull request by skalad**
just sth I didnt find already made and the only solution I found to use pan-tilt without extra hardware in Raspberry Pi Model 2

### CODE REVIEW

**Comment by spex357** [comment]
Hi Skalad, I have ServoBlaster running and have installed your git on my Pi-B. I didn't get the normal Apache/ Nginx menu on install that I get on the standard RPi-Cam install, and didn't get anything on my web browser on reboot. So I installed Apache using part of the script in the Installer. Apache is now on the web browser but not connected with RPI-Cam files in /var/www. A file is being updated in /dev/shm/mjpg so i'm not far away. What file do I need to edit? any ideas would be useful

**Comment by skalad** [comment]
mmmmm

Is the camera enabled?

sudo raspi-config

Use the cursor keys to move to the camera option, and select enable. On exiting raspi-config, it will ask to reboot.

**Comment by skalad** [comment]
What is exactly appearing in the web/browser? probably is just apache configuration?.... apache sites available, sites enabled and all this configuration files. and it depends if it is apache or apache2 it should be done different,  is php module enabled? install libapache2-mod-php5. I dont know exactly what is happening. and long time without using this project but ill try to help

**Comment by roberttidey** [comment]
The other factor here is whether this was installed on Wheezy or Jessie version of Rasbian. Jessie changed around quite a bit of stuff which broke a lot of the install on the base RPI_Cam

**Comment by spex357** [comment]
rpi
Hey thanks for the speedy response guys.
I am on Jessie, I did wonder if I should drop back to Wheezy or further?
I have also been experimenting with the Linux RPI_Cam version which shows the menu with no problem. I have run... Installer autorun but that didn't take effect. If I run .sh start then a file is updated in /dev/shm/mjpeg. As Apache is mention in the script then I find it hard to imagine that it was missed on install. 
Yes the browser now shows an Apache Index page. I have got further than this with the normal Git, but fail again at the direction arrows, they are there in blue, but not active but I didn't have the control in servoblaster as good as I have at the moment, but i'm sure I could suss how or why that is the case.
In the RPI Git install running .sh install in terminal or the Gui desktop, brings me back to the choices menu, not as in the picture.

**Comment by spex357** [comment]
Update: Auto doesn't work, start generates a file in mjpeg and it is constantly updated, browser is still on Apache index.

**Comment by skalad** [comment]
It would be better to separate it in 2 parts to find and fix the problems,

1 RPi_Cam_Web_Interface https://github.com/silvanmelchior/RPi_Cam_Web_Interface
I would start triying this alone.

2 Pan/tilt controls Web Interface 
Once RPi_Cam_Web_Interface works propperly without pan titl controls the only thing my fork makes is adding a Web_pantilt_control frame in /var/www/index.php 

   <frame name="webcam" src="/webcam.php" /> this is the original 1 web cam interface page
   <frame name="control" src="/control-child.php" /> this is the pan/tilt 2 control web page

the only thing the second frame control-child.php makes is showing the green control arrows and when they are clicked it calls a bash scripts with exec ('sh /var/www/script.sh') this bash scripts use servoblaster to move the pan/tilt and keep a journal of the servos position in a txt file.

**Comment by spex357** [comment]
I am as I type just running apt-get dist upgrade on my way to installing Servoblaster and the Linux RPI base git on another card. It's the config menu that didn't show on install and I couldn't access it in the gui desktop either, all a bit odd. I have mentioned before, I have had the placeholders for the buttons on a previous attempt and have shot an IR timelapse, i'm sure I can get back to that point.

**Comment by roberttidey** [comment]
I agree it is best to separate the issues here. Get the basic i/f going then get the Servoblaster how you want.

The base RPi install has an alternative install method available which has had more work done it to make it Jessie compatible. See wiki for details

**Comment by spex357** [comment]
So far so good, picture is updating, config menu works for start and stop, now to activate the buttons?
buttons

**Comment by spex357** [comment]
A new day, autostart has been enabled, I have control of the servos with SB but not in the browser.

**Comment by skalad** [comment]
If using my fork, Try executing the scripts that are beeing callled by the php code like up.sh down.sh, etc... in order to do that, go to the /var/www/ path and execute them directly in the command line. If they work, chmod them to any user acces them, probably what happens is that the php application server server form nginx/apache needs special rights for it. If not... check that php exec is working and calling the script when triggered in the php page. regards...

**Comment by spex357** [comment]
Much later in the day, files deleted and some renamed and now I have limited movement in the browser. One click in either direction plus its return.
https://youtu.be/qThpZBMLHWU

**Comment by spex357** [comment]
A late night after re-installing your fork. In Terminal and GUI I can access left.sh and right but up and down do nothing, the two file's don't even double click?. In the browser I am still stuck on the Debian Apache start html file which is in /var/www/html/. I have searched this problem before, it's mentioned in lots of places but there's no answers. It has been so common an occurrence on numerous forks  I am amazed I haven't got it nailed. Yesterday pipan_off and pipan_on and servo_off and servo_on where all in the folder together, After leaving it at servo_on and pipan_off the RPI_Cam fork came into life with some limited movement in the browser. I don't have a servo_ in this fork so pipan_on is in force.

**Comment by roberttidey** [comment]
Not clear which fork you are talking about.

I would start not with a fork but instead install the root version here which does work with Jessie. The alternate install instructions as per the wiki are also a bit more Jessie friendly.

Once you have that fully working Ok then start the pan/tilt stuff either by making the skalad mods or by enabling the support here using pipan_on or servo_on files.

**Comment by spex357** [comment]
Yes I have two on the go. The Linux RPi_Cam I have up and running, but with very limited movement on the servo via the browser. I'm not sure why.
This morning has been a Skalad fork attempt, I have just ./...sh remove.sh and rebooted after a normal install got me to the Apache Debian html (different from below) then ./...sh install.sh
and rebooted and i'm at the Apache start html. The camera is on autostart and working but not feeding into the browser or the correct browser isn't being loaded.
index

**Comment by roberttidey** [comment]
By Linux RPi Cam I assume you mean the standard one here.

I don't think the skalad fork is fully Jessie aware. There were some significant changes in Jessie compared to Wheezy which broke a lot of the install including the Apache web server settings and will lead to the problems you are seeing.

I would continue with the one you have working but concentrate on why you are getting limited movement on the pan / tilt. What do you mean by that? Not all buttons working? Range of movement is  restricted? Those things are probably easier to check out.

**Comment by spex357** [comment]
Hi Robert, thanks for the interest. I have a video posted above which shows the limit of my movement in the base distro. It allows one movement in either direction and then its return. 
If I access l&r and u&d .sh in Gui desktop by double clicking, left and right seem to work ok. The up and down files will highlight and nothing else.
If I access them by the terminal l&r work ok even though they return a permission denied quoting line 14 and 15 respectively. U&d return a no such file or directory. All very odd.

**Comment by roberttidey** [comment]
Assuming you are using servo_blaster mode (servo_on file present, but no pipan_on) present then this is supposed to work as follows.

1) The local browser pan / tilt are set to 100,100

1) Clicking on buttons can cause a request to be made to pipan.php on server. This should just have an action keyword and a value of left, right, up, down. The command is only sent if the local pan / tilt is between 10 and 190 to limit movement. If the command is sen then the pan / tilt get 10 added or subtracted.

2) pipan.php reads the servo_on file to extract the current x,y co-ordinates or assumes they are 165,165 if they don't exist.

3) It then adds or subtracts 10 to the relevant co-ordinate and writes this into the servoblaster pipe at /dev/servoblaster

To see why this is not working for you there are several things you can do.

a) Turn on Development tools in browser. This will show the actions requests being sent to the browser.

b) Check the contents of the servo_on file after button presses. It should be updating.

Also check permissions on the servo_on file. It should be owned by www-data and have read/write permissions. If not then try sudo chown www-data:www-data servo_on

**Comment by spex357** [comment]
Hi Robert
l r
u d


There is nothing inside the servo_on file and nothing happens during button presses :-(

**Comment by spex357** [comment]
The only other thing I did was permissions and it is now working ok

**Comment by skalad** [comment]
I just got home... I have the RPi here. This week I´ll play with RPi to install the silvanmelchior/RPi_Cam_Web_Interface with servos, servoblaster and camera. long time without using it... I didnt know it had servoblaster support already. looks nice...

**Comment by spex357** [comment]
i installed servoblaster before RPi on both attempts. I hadn't noticed it already had a SB file in the folder

**Comment by spex357** [comment]
I don't think there is much wrong with the Skalad fork. My initial re-install of Apache was only down to me thinking it hadn't been installed as I couldn't access config through the installer like I do in the base distro. 
config 
Which is how I normally install it, stop it and start it. To re-install Apache, I cut the code out of the install script and it installed ok. It over wrote the Apache page shown above with a Debian version.

Skalad is running but not on auto even though I have set it more than once. Mjpeg is being updated, Servoblaster is installed but there is no servo_on in the folder, which probably explains why i'm stuck on the Apache page shown above.
 Looking in the Base Distro servo_on file it was empty, Can I make one and set permissions etc?
In the quest for sexy green buttons I can just copy the files over I suppose?

**Comment by roberttidey** [comment]
I don't think the skalad fork uses the servo_on file. 

The base distribution has files called pipan_off servo_off as by default the pan tilt support is off. 

To use with original pipan mechanism one just renames pipan_off to pipan_on.
To use with servoblaster one just renames servo_off to on (leaving pipan_off alone)

The servo_on is initially empty but on first use is populated with x,y 165,165 and is then updated as movements are made. Its permissions should be www-data r/w which is the permissions of the servo_off as distributed.

When installing the base distribution one can use ./install.sh instead of the previous script. This does the config and install all in one go.

**Comment by spex357** [comment]
Hi Robert
yes I tried both ways yesterday on the base distro and your little list including setting permissions got me off the Debian index page and up and running. Is the permissions problem responsible for not loading the correct html page on initial reboot? I have seen this in forums, and experienced it myself many times. I have had numerous attempts since last year to get this running and have always given up and gone experimenting with other camera distro's. With yours and Skalads help i'm up and running in three days. A big thanks to you both.
I'm now going to format a card, install Jessie, don't install Servoblaster  and see how it goes.

Noted servo_on is un-populated until your running (populated today) and servo_on not being present on Skalads fork 
Ignore my thoughts on copying the green buttons over, looking in the html, the base arrows aren't jpg's.

**Comment by spex357** [comment]
debian
I followed Silvans git, didn't install servoBlaster rebooted and landed on the Debian page above.
In Gui desktop, double click Installer, pick open in terminal, pick update and upgrade cam in config menu, set auto start, reboot.
Browser is live with no buttons
/var/www/html tools run command sudo mv servo_off servo_on
run command sudo rm -rf servo_off
reboot
Browser is live with buttons returning 192... pipan.php for all directions.

**Comment by roberttidey** [comment]
Are you installing into a subfolder of the web DocumentRoot (/var/www)? If so then the url should contain the subfolder. E.g. if you install into rpi then this goes into /var/www/rpi and the url should be http://hostname/rpi  This was the popular method with wheezy as it allowed having multiple different web sites under apache selectable just by adding the subfolder onto the url

This is a confusing area as with Jessie the default DocumentRoot is now /var/www/html. The ./install.sh method resets this back to /var/www so it behaves similarly to Wheezy. I think with the previous install script you must configure html as a subfolder for the install and then you use http://hostname

**Comment by spex357** [comment]
An interesting morning, had to remove and install servoblaster first (possibly) before RPi. I was incorrectly wired on the breadboard so it may not have needed it. Having missed it out on Silvans install. I installed it afterwards but didn't get it to work, not double checking wire I removed RPi in Gui rebooted and re installed when I noticed the wire. After a servo test, all was well after renaming servo_off.
I am in default setting, any myriad of reasons are possible as to why I've failed so many times before, but I am much happier in Terminal than I was say three months ago.
Would changing the name of servo_on, hold the page without a permissions change, I forgot to find out, does mv take that info with it?

**Comment by spex357** [comment]
I've just realised we are in Skalads fork and I've now written over the sdcard so I suppose we are closed.
Skalads fork was working apart from making the final connection

**Pull request closed without merging**
