### PR TITLE
rc.local improvement

### PR DESCRIPTION
**Pull request by miraaz**
roberttidey. Please test my rc.local hack. I tested with intepentent script and worked like charm. If you also happy with that then lets shange install sections also.
I not like that replace original config file stuff and that is first step to get rid of that.

### CODE REVIEW

**Comment by roberttidey** [comment]
This is not to do with your changes but I just tested the installer and found the install rc.local handling seems to be bust at the moment. It looks to me like the awk line is not doing what is expected and one ends up with a blank rc.local. I also saw that it was directly editing the rc.local.1 which didn't seem like a good idea as it could end up with subfolders getting duplicated if the original file was not updated first.

I have reverted just that bit to the original overwriting method, but I think this is what you were looking at so hopefully we can re-introduce this shortly.

**Comment by miraaz** [comment]
You can run my method running installer with autostart option and look changes in rc.local. For me its working perfectly. 
1. test i enabled autostart meny times in row and result ok
2. test i disabled autostart meny times in row and result ok
3. testi swiched on and of autostart and again ok.
4. test changed rpicamdir="" (nothing) in config.txt result is fine.
5 test changed rpicam="test" in config.txt and test result was perfect.
I not noticed bugs no mather how i runned script.
Tish version script cleans, when disable autostart, rc.local fully and compatible also older already replaced rc.local.
I think we can implement that also in install section and send that "cp rc.local.1" stuff in recyle. Please test autostart option and say if you found some bug. 

N.B. i readed forum and seems people not happy about that webroot idea. It makes problems when people wants run more websites when only rpicam...

**Comment by roberttidey** [comment]
I've merged this one. It's the base install that is broken. I think it relied on a rc.local already being there which is not the case with a totally clean install.

**Comment by miraaz** [comment]
rc.local always in /etc/rc.local. Even when clean install. My autostart option only edits that in place.

**Pull request merged**
