### PR TITLE
Improvements rc.local

### PR DESCRIPTION
**Pull request by miraaz**
Removed autostart yes/no and added all configuration in separate option configure. Lot of changes! I houpe all working.
rc.local now not replaced and users custom shanges surive there.
If all working fine we can delete etc/rc_local_run/* at all :).

### CODE REVIEW

**Comment by roberttidey** [comment]
Quite big changes there and it overlapped with the recent work also on preserving rc.local contents.

I wonder whether we should try to get somebody on the forum to give it a try before pushing it out. I think one should be able to just download a zip of it independently. Providing one doesn't do an update then one could test it out.

**Comment by miraaz** [comment]
rc.local contents is basically same. Only added it in function. Then i disable and enable it.
rc.local i tested with in separate script and worked fine. I not tested all together yet.
Now rc.local not replaced like before. Uninstall or stop time i simple disable function. I try test full script soon.
I think overload script with start options not smart. Thats why i removed autostart options and added all options in configure.

**Comment by miraaz** [comment]
Btw old rc.local script was buggy anyway. I noticed it was full repeated start scripts! I think that happens because several times over install and not uninstall first. That means disable autostart not was possible anymore without clean manually rc.local first.

**Comment by miraaz** [comment]
Do not push it! Its buggy! Do not remove push request also please. I start fix it. Lets try bush small changes at time.

**Pull request closed without merging**
